### ISSUE TITLE
manually freeing up alarm 

### ISSUE THREAD

**Issue by mckennatim** [PaulStoffregen/TimeAlarms#10]
Is there a simple call to free up the ids & memory and end all the alarms? I can see that the TimeAlarmsClass constructor does just that. Not sure how to call it though. 

(so I forked the repo and copied the constructor as `void TimeAlarmsClass::clear()` and now whenever the the client app wants to reschedule all the alarms I call that first. Otherwise the alarms that never got triggered just took up space and accumulated)

**Comment by PaulStoffregen** [comment]
Yes, TimeAlarmsClass::free()

**Comment by mckennatim** [comment]
TimeAlarmsClass::free(AlarmID_t ID) needs an ID no? I didn't want to have to keep track of the ID's, and needed to clear them all.
