### ISSUE TITLE
Set the time once

### ISSUE THREAD

**Issue by jarandacu** [PaulStoffregen/TimeAlarms#27]
Hi ! 

I want to set the time just once in the arduino and then just execute the alarm program, how i can do that ?? i tried:

1. comment the set time:
//setTime(9,30,00,17,3,17);
But does not work, the time reset to 0:0:0.
2. No argument
setTime();
it cant be compiled. 

Some help ?? Grettings !

**Comment by PaulStoffregen** [comment]
Github issues are not the place to ask for help.  Use the forums.  DO NOT ask here.

When you post on the forum, give your complete program.  Nobody can help with this incomplete info.
