### ISSUE TITLE
Alarm.delay() failed ArduinoOTA

### ISSUE THREAD

**Issue by eric4v** [PaulStoffregen/TimeAlarms#35]
I make a test with BasicOTA.ino and it work fine on my Wemos D1 mini  

I modified the sketch with 
...
#include <TimeLib.h>  
#include <TimeAlarms.h
...
void loop() {
  ArduinoOTA.handle();
  Alarm.delay(1000);
}

And my wemos don't appear on network port

**Comment by PaulStoffregen** [comment]
Check your copy of this lib.  Does it have this patch?
https://github.com/PaulStoffregen/TimeAlarms/commit/bd9511040460c41be72d899899f48a7ead436708

**Comment by eric4v** [comment]
I m using library v1.5.0 with Arduino 1.8.5  (on ubuntu) not propose update and I don't have this patch. 
The problems is solved by this patch.
