### ISSUE TITLE
Setting time and changing alarm time

### ISSUE THREAD

**Issue by Prithul0218** [PaulStoffregen/TimeAlarms#5]
Hello! I am Prithul, from Bangladesh. I have 2 questions-

1) How can I make the program so that the time library automatically gets the time from my computer?

2) I am making a project which will turn on a light at a fixed time. It will have an LCD and some buttons. I wanna set the alarm time by pressing the buttons (for example - pressing a button will increase the hour by 1) But my question is how can I change the alarms time once it has been set?

**Comment by PaulStoffregen** [comment]
If using Arduino, ask here: http://forum.arduino.cc/index.php?board=3.0
If using Teensy, ask here: https://forum.pjrc.com/forum.php

This is only for reporting problems or contribution to the library.  Do not ask usage questions here.
