### ISSUE TITLE
Can set only one alarm on a weekday

### ISSUE THREAD

**Issue by Luis-Castillo** [PaulStoffregen/TimeAlarms#6]
Tried to set two alarms on the same weekday with Alarm.alarmRepeat, but only the fist one fires.

**Comment by PaulStoffregen** [comment]
Please post a program which demonstrates this error.

**Comment by Luis-Castillo** [comment]
I don't have that code anymore and couldn't replicate the scenario. I'm guessing it might have been a bug in my code, not the library. If it comes up again I'll let you know. Sorry.
